name: LoginSystem
version: 1.3
main: me.bartuabihd.loginsystem.LoginSystem
api-version: 1.13
author: BartuAbiHD
description: Gelişmiş ve çoklu veritabanı destekli kimlik doğrulama eklentisi.

commands:
  login:
    description: Sunucuya giriş yapmanızı sağlar.
    usage: /login <password>
    aliases: [l]
  register:
    description: Sunucuya kayıt olmanızı sağlar.
    usage: /register <password> <confirmPassword>
    aliases: [reg]
  unregister:
    description: Sunucudaki kaydınızı siler.
    usage: /unregister <password>
  logout:
    description: Güvenli çıkış yapmanızı sağlar.
  changepassword:
    description: Şifrenizi değiştirmenizi sağlar.
    usage: /changepassword <oldPassword> <newPassword>
    aliases: [changepass, changepw]
  email:
    description: Email adresinizi yönetmenizi sağlar.
    usage: /email <add|change> <emailAdress>